name: chat_rawro
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^1.3.0
  cloud_firestore: ^1.0.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
